project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "casa0023_learning_diary"
  navbar:
    left:
      - href: week2.qmd
        text: "week2"
      - href: week4.qmd
        text: "week4"
      - href: week6.qmd
        text: "week6"
      - href: week7.qmd
        text: "week7"
format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true


