project:
  type: website
  output-dir: docs

website:
  title: "casa0023_learning_diary"
  navbar:
    left:
      - href: week2.qmd
        text: "week2"
      - href: week4.qmd
        text: "week4"
format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true


