project:
  type: website
  output-dir: docs

website:
  title: "casa0023_learning_diary"
  navbar:
    left:
      - text: Weekly Notes
        menu:
          - href: week4.qmd
            text: Week 4

format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true


